---
galaxy_info:
  role_name: sendguard
  author: PERULINUX
  description: Despliegue del agente SendGuard (protección SMTP/IMAP para Zimbra)
  license: proprietary
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions: ["8", "9"]
    - name: Ubuntu
      versions: ["all"]
dependencies: []
